### ISSUE TITLE
Create database model

### ISSUE THREAD

**Issue by muyunli123** [CSCI-GA-2820-FA24-003/recommendations#1]
**As an** developer
**I need** to create database model for recommendation API
**So that** the recommendation data can be retrieved correctly by users
   
 ### Details and Assumptions
The database model should contain 2 tables: 
 * Recommendation table: id of a basic product and a recommended product, and their recommendation type, e.g., cross-sell, up-sell, accessory
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the table schemas 
 When database is created
 Then querying and transactions can be performed on the database
```

**Comment by agustdmybae** [comment]
Feedback from Prof:
Creating one table is fine. 
We can directly use the Product service with the given product ID.
