### ISSUE TITLE
Implement Like Action endpoint route

### ISSUE THREAD

**Issue by muyunli123** [CSCI-GA-2820-FA24-003/recommendations#25]
**As a** customer
**I need** capability to like a listed recommendation
**So that** I can share my feedback towards the recommendation
   
 ### Details and Assumptions
We need the ability to perform the following action on recommendations
 * like a recommendation
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the ability to like a recommendation
 When an action is performed
 Then the number of likes of the corresponding recommendation increases
```

**Comment by agustdmybae** [comment]
Have to discuss whether adding new attributes to database model

**Comment by agustdmybae** [comment]
Details to implement Like Action:
- Add like section in DB, which stores a boolean value (default False)
- User perform like action > Check if like is False then update to true, vice versa
